// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IGDBProtoFile.proto

package proto;

public interface CharacterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Character)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>repeated string akas = 2;</code>
   */
  java.util.List<java.lang.String>
      getAkasList();
  /**
   * <code>repeated string akas = 2;</code>
   */
  int getAkasCount();
  /**
   * <code>repeated string akas = 2;</code>
   */
  java.lang.String getAkas(int index);
  /**
   * <code>repeated string akas = 2;</code>
   */
  com.google.protobuf.ByteString
      getAkasBytes(int index);

  /**
   * <code>string countryName = 3;</code>
   */
  java.lang.String getCountryName();
  /**
   * <code>string countryName = 3;</code>
   */
  com.google.protobuf.ByteString
      getCountryNameBytes();

  /**
   * <code>.google.protobuf.Timestamp createdAt = 4;</code>
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp createdAt = 4;</code>
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp createdAt = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>string description = 5;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated .proto.Game games = 6;</code>
   */
  java.util.List<proto.Game> 
      getGamesList();
  /**
   * <code>repeated .proto.Game games = 6;</code>
   */
  proto.Game getGames(int index);
  /**
   * <code>repeated .proto.Game games = 6;</code>
   */
  int getGamesCount();
  /**
   * <code>repeated .proto.Game games = 6;</code>
   */
  java.util.List<? extends proto.GameOrBuilder> 
      getGamesOrBuilderList();
  /**
   * <code>repeated .proto.Game games = 6;</code>
   */
  proto.GameOrBuilder getGamesOrBuilder(
      int index);

  /**
   * <code>.proto.GenderGenderEnum gender = 7;</code>
   */
  int getGenderValue();
  /**
   * <code>.proto.GenderGenderEnum gender = 7;</code>
   */
  proto.GenderGenderEnum getGender();

  /**
   * <code>.proto.CharacterMugShot mugShot = 8;</code>
   */
  boolean hasMugShot();
  /**
   * <code>.proto.CharacterMugShot mugShot = 8;</code>
   */
  proto.CharacterMugShot getMugShot();
  /**
   * <code>.proto.CharacterMugShot mugShot = 8;</code>
   */
  proto.CharacterMugShotOrBuilder getMugShotOrBuilder();

  /**
   * <code>string name = 9;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 9;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .proto.Person people = 10;</code>
   */
  java.util.List<proto.Person> 
      getPeopleList();
  /**
   * <code>repeated .proto.Person people = 10;</code>
   */
  proto.Person getPeople(int index);
  /**
   * <code>repeated .proto.Person people = 10;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .proto.Person people = 10;</code>
   */
  java.util.List<? extends proto.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .proto.Person people = 10;</code>
   */
  proto.PersonOrBuilder getPeopleOrBuilder(
      int index);

  /**
   * <code>string slug = 11;</code>
   */
  java.lang.String getSlug();
  /**
   * <code>string slug = 11;</code>
   */
  com.google.protobuf.ByteString
      getSlugBytes();

  /**
   * <code>.proto.CharacterSpeciesEnum species = 12;</code>
   */
  int getSpeciesValue();
  /**
   * <code>.proto.CharacterSpeciesEnum species = 12;</code>
   */
  proto.CharacterSpeciesEnum getSpecies();

  /**
   * <code>.google.protobuf.Timestamp updatedAt = 13;</code>
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 13;</code>
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 13;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>string url = 14;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 14;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
