// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IGDBProtoFile.proto

package proto;

public interface PlatformVersionCompanyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PlatformVersionCompany)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string comment = 2;</code>
   */
  java.lang.String getComment();
  /**
   * <code>string comment = 2;</code>
   */
  com.google.protobuf.ByteString
      getCommentBytes();

  /**
   * <code>.proto.Company company = 3;</code>
   */
  boolean hasCompany();
  /**
   * <code>.proto.Company company = 3;</code>
   */
  proto.Company getCompany();
  /**
   * <code>.proto.Company company = 3;</code>
   */
  proto.CompanyOrBuilder getCompanyOrBuilder();

  /**
   * <code>bool developer = 4;</code>
   */
  boolean getDeveloper();

  /**
   * <code>bool manufacturer = 5;</code>
   */
  boolean getManufacturer();
}
