
/**
 * Endpoint
 * Lets users access public Endpoints
 *
 * Created at: 2018-01-03
 *
 * Created by Filip
 *
 **/
enum class Endpoint {
    ACHIEVEMENTS, ACHIEVEMENT_ICONS, AGE_RATINGS, AGE_RATING_CONTENT_DESCRIPTIONS, ALTERNATIVE_NAMES, ARTWORKS,
    CHARACTERS, CHARACTER_MUG_SHOTS, COLLECTIONS, COMPANIES, COMPANY_WEBSITES, COMPANY_LOGOS, COVERS, EXTERNAL_GAMES,
    FEEDS, FRANCHISES, GAMES, GAME_ENGINES, GAME_ENGINE_LOGOS, GAME_MODES, GAME_VERSIONS, GAME_VERSION_FEATURES,
    GAME_VERSION_FEATURE_VALUES, GAME_VIDEOS, GENRES, INVOLVED_COMPANIES, KEYWORDS, MULTIPLAYER_MODES, PAGES,
    PAGE_BACKGROUNDS, PAGE_LOGOS, PAGE_WEBSITES, PLATFORMS, PLATFORM_LOGOS, PLATFORM_VERSIONS,
    PLATFORM_VERSION_COMPANIES, PLATFORM_VERSION_RELEASE_DATES, PLATFORM_WEBSITES, PLAYER_PERSPECTIVES, PRODUCT_FAMILIES,
    PULSES, PULSE_GROUPS, PULSE_SOURCES, PULSE_URLS, RELEASE_DATES, SCREENSHOTS, SEARCH, THEMES, TIME_TO_BEATS, TITLES,
    WEBSITES
}

/**
 * PrivateEndpoint
 * Lets users access private Endpoints
 *
 * Created at: 2018-01-03
 *
 * Created by Filip
 *
 **/
enum class PrivateEndpoint {
    CREDITS, FEED_FOLLOWS, FOLLOWS, LISTS, LIST_ENTRIES, PEOPLE, PERSON_MUG_SHOTS, PERSON_WEBSITES, RATES, REVEIWS,
    REVIEW_VIDEOS, SOCIAL_METRICS,
}
