// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/api/igdb/igdbproto.proto

package proto;

/**
 * Protobuf type {@code proto.GameLocalizationResult}
 */
public final class GameLocalizationResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.GameLocalizationResult)
    GameLocalizationResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GameLocalizationResult.newBuilder() to construct.
  private GameLocalizationResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameLocalizationResult() {
    gamelocalizations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GameLocalizationResult();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Igdbproto.internal_static_proto_GameLocalizationResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Igdbproto.internal_static_proto_GameLocalizationResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.GameLocalizationResult.class, proto.GameLocalizationResult.Builder.class);
  }

  public static final int GAMELOCALIZATIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<proto.GameLocalization> gamelocalizations_;
  /**
   * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
   */
  @java.lang.Override
  public java.util.List<proto.GameLocalization> getGamelocalizationsList() {
    return gamelocalizations_;
  }
  /**
   * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.GameLocalizationOrBuilder> 
      getGamelocalizationsOrBuilderList() {
    return gamelocalizations_;
  }
  /**
   * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
   */
  @java.lang.Override
  public int getGamelocalizationsCount() {
    return gamelocalizations_.size();
  }
  /**
   * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
   */
  @java.lang.Override
  public proto.GameLocalization getGamelocalizations(int index) {
    return gamelocalizations_.get(index);
  }
  /**
   * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
   */
  @java.lang.Override
  public proto.GameLocalizationOrBuilder getGamelocalizationsOrBuilder(
      int index) {
    return gamelocalizations_.get(index);
  }

  public static proto.GameLocalizationResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GameLocalizationResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GameLocalizationResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GameLocalizationResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GameLocalizationResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GameLocalizationResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GameLocalizationResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.GameLocalizationResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.GameLocalizationResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.GameLocalizationResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.GameLocalizationResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.GameLocalizationResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.GameLocalizationResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.GameLocalizationResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GameLocalizationResult)
      proto.GameLocalizationResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Igdbproto.internal_static_proto_GameLocalizationResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Igdbproto.internal_static_proto_GameLocalizationResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GameLocalizationResult.class, proto.GameLocalizationResult.Builder.class);
    }

    // Construct using proto.GameLocalizationResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (gamelocalizationsBuilder_ == null) {
        gamelocalizations_ = java.util.Collections.emptyList();
      } else {
        gamelocalizations_ = null;
        gamelocalizationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Igdbproto.internal_static_proto_GameLocalizationResult_descriptor;
    }

    @java.lang.Override
    public proto.GameLocalizationResult getDefaultInstanceForType() {
      return proto.GameLocalizationResult.getDefaultInstance();
    }

    @java.lang.Override
    public proto.GameLocalizationResult build() {
      proto.GameLocalizationResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.GameLocalizationResult buildPartial() {
      proto.GameLocalizationResult result = new proto.GameLocalizationResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(proto.GameLocalizationResult result) {
      if (gamelocalizationsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          gamelocalizations_ = java.util.Collections.unmodifiableList(gamelocalizations_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.gamelocalizations_ = gamelocalizations_;
      } else {
        result.gamelocalizations_ = gamelocalizationsBuilder_.build();
      }
    }

    private void buildPartial0(proto.GameLocalizationResult result) {
      int from_bitField0_ = bitField0_;
    }

    private int bitField0_;

    private java.util.List<proto.GameLocalization> gamelocalizations_ =
      java.util.Collections.emptyList();
    private void ensureGamelocalizationsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        gamelocalizations_ = new java.util.ArrayList<proto.GameLocalization>(gamelocalizations_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.GameLocalization, proto.GameLocalization.Builder, proto.GameLocalizationOrBuilder> gamelocalizationsBuilder_;

    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public java.util.List<proto.GameLocalization> getGamelocalizationsList() {
      if (gamelocalizationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(gamelocalizations_);
      } else {
        return gamelocalizationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public int getGamelocalizationsCount() {
      if (gamelocalizationsBuilder_ == null) {
        return gamelocalizations_.size();
      } else {
        return gamelocalizationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public proto.GameLocalization getGamelocalizations(int index) {
      if (gamelocalizationsBuilder_ == null) {
        return gamelocalizations_.get(index);
      } else {
        return gamelocalizationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public Builder setGamelocalizations(
        int index, proto.GameLocalization value) {
      if (gamelocalizationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGamelocalizationsIsMutable();
        gamelocalizations_.set(index, value);
        onChanged();
      } else {
        gamelocalizationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public Builder setGamelocalizations(
        int index, proto.GameLocalization.Builder builderForValue) {
      if (gamelocalizationsBuilder_ == null) {
        ensureGamelocalizationsIsMutable();
        gamelocalizations_.set(index, builderForValue.build());
        onChanged();
      } else {
        gamelocalizationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public Builder addGamelocalizations(proto.GameLocalization value) {
      if (gamelocalizationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGamelocalizationsIsMutable();
        gamelocalizations_.add(value);
        onChanged();
      } else {
        gamelocalizationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public Builder addGamelocalizations(
        int index, proto.GameLocalization value) {
      if (gamelocalizationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGamelocalizationsIsMutable();
        gamelocalizations_.add(index, value);
        onChanged();
      } else {
        gamelocalizationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public Builder addGamelocalizations(
        proto.GameLocalization.Builder builderForValue) {
      if (gamelocalizationsBuilder_ == null) {
        ensureGamelocalizationsIsMutable();
        gamelocalizations_.add(builderForValue.build());
        onChanged();
      } else {
        gamelocalizationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public Builder addGamelocalizations(
        int index, proto.GameLocalization.Builder builderForValue) {
      if (gamelocalizationsBuilder_ == null) {
        ensureGamelocalizationsIsMutable();
        gamelocalizations_.add(index, builderForValue.build());
        onChanged();
      } else {
        gamelocalizationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public Builder addAllGamelocalizations(
        java.lang.Iterable<? extends proto.GameLocalization> values) {
      if (gamelocalizationsBuilder_ == null) {
        ensureGamelocalizationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, gamelocalizations_);
        onChanged();
      } else {
        gamelocalizationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public Builder clearGamelocalizations() {
      if (gamelocalizationsBuilder_ == null) {
        gamelocalizations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        gamelocalizationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public Builder removeGamelocalizations(int index) {
      if (gamelocalizationsBuilder_ == null) {
        ensureGamelocalizationsIsMutable();
        gamelocalizations_.remove(index);
        onChanged();
      } else {
        gamelocalizationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public proto.GameLocalization.Builder getGamelocalizationsBuilder(
        int index) {
      return getGamelocalizationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public proto.GameLocalizationOrBuilder getGamelocalizationsOrBuilder(
        int index) {
      if (gamelocalizationsBuilder_ == null) {
        return gamelocalizations_.get(index);  } else {
        return gamelocalizationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public java.util.List<? extends proto.GameLocalizationOrBuilder> 
         getGamelocalizationsOrBuilderList() {
      if (gamelocalizationsBuilder_ != null) {
        return gamelocalizationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(gamelocalizations_);
      }
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public proto.GameLocalization.Builder addGamelocalizationsBuilder() {
      return getGamelocalizationsFieldBuilder().addBuilder(
          proto.GameLocalization.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public proto.GameLocalization.Builder addGamelocalizationsBuilder(
        int index) {
      return getGamelocalizationsFieldBuilder().addBuilder(
          index, proto.GameLocalization.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.GameLocalization gamelocalizations = 1;</code>
     */
    public java.util.List<proto.GameLocalization.Builder> 
         getGamelocalizationsBuilderList() {
      return getGamelocalizationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.GameLocalization, proto.GameLocalization.Builder, proto.GameLocalizationOrBuilder> 
        getGamelocalizationsFieldBuilder() {
      if (gamelocalizationsBuilder_ == null) {
        gamelocalizationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.GameLocalization, proto.GameLocalization.Builder, proto.GameLocalizationOrBuilder>(
                gamelocalizations_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        gamelocalizations_ = null;
      }
      return gamelocalizationsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.GameLocalizationResult)
  }

  // @@protoc_insertion_point(class_scope:proto.GameLocalizationResult)
  private static final proto.GameLocalizationResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.GameLocalizationResult();
  }

  public static proto.GameLocalizationResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameLocalizationResult>
      PARSER = new com.google.protobuf.AbstractParser<GameLocalizationResult>() {
    @java.lang.Override
    public GameLocalizationResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameLocalizationResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameLocalizationResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.GameLocalizationResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

