// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IGDBProtoFile.proto

package proto;

public interface GameVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GameVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional .google.protobuf.Timestamp createdAt = 2;</code>
   */
  boolean hasCreatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp createdAt = 2;</code>
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp createdAt = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>repeated .proto.GameVersionFeature features = 3;</code>
   */
  java.util.List<proto.GameVersionFeature> 
      getFeaturesList();
  /**
   * <code>repeated .proto.GameVersionFeature features = 3;</code>
   */
  proto.GameVersionFeature getFeatures(int index);
  /**
   * <code>repeated .proto.GameVersionFeature features = 3;</code>
   */
  int getFeaturesCount();
  /**
   * <code>repeated .proto.GameVersionFeature features = 3;</code>
   */
  java.util.List<? extends proto.GameVersionFeatureOrBuilder> 
      getFeaturesOrBuilderList();
  /**
   * <code>repeated .proto.GameVersionFeature features = 3;</code>
   */
  proto.GameVersionFeatureOrBuilder getFeaturesOrBuilder(
      int index);

  /**
   * <code>optional .proto.Game game = 4;</code>
   */
  boolean hasGame();
  /**
   * <code>optional .proto.Game game = 4;</code>
   */
  proto.Game getGame();
  /**
   * <code>optional .proto.Game game = 4;</code>
   */
  proto.GameOrBuilder getGameOrBuilder();

  /**
   * <code>repeated .proto.Game games = 5;</code>
   */
  java.util.List<proto.Game> 
      getGamesList();
  /**
   * <code>repeated .proto.Game games = 5;</code>
   */
  proto.Game getGames(int index);
  /**
   * <code>repeated .proto.Game games = 5;</code>
   */
  int getGamesCount();
  /**
   * <code>repeated .proto.Game games = 5;</code>
   */
  java.util.List<? extends proto.GameOrBuilder> 
      getGamesOrBuilderList();
  /**
   * <code>repeated .proto.Game games = 5;</code>
   */
  proto.GameOrBuilder getGamesOrBuilder(
      int index);

  /**
   * <code>optional .google.protobuf.Timestamp updatedAt = 6;</code>
   */
  boolean hasUpdatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp updatedAt = 6;</code>
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp updatedAt = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>optional string url = 7;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>optional string url = 7;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
