// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IGDBProtoFile.proto

package proto;

public interface InvolvedCompanyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.InvolvedCompany)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional .proto.Company company = 2;</code>
   */
  boolean hasCompany();
  /**
   * <code>optional .proto.Company company = 2;</code>
   */
  proto.Company getCompany();
  /**
   * <code>optional .proto.Company company = 2;</code>
   */
  proto.CompanyOrBuilder getCompanyOrBuilder();

  /**
   * <code>optional .google.protobuf.Timestamp createdAt = 3;</code>
   */
  boolean hasCreatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp createdAt = 3;</code>
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp createdAt = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>optional bool developer = 4;</code>
   */
  boolean getDeveloper();

  /**
   * <code>optional .proto.Game game = 5;</code>
   */
  boolean hasGame();
  /**
   * <code>optional .proto.Game game = 5;</code>
   */
  proto.Game getGame();
  /**
   * <code>optional .proto.Game game = 5;</code>
   */
  proto.GameOrBuilder getGameOrBuilder();

  /**
   * <code>optional bool porting = 6;</code>
   */
  boolean getPorting();

  /**
   * <code>optional bool publisher = 7;</code>
   */
  boolean getPublisher();

  /**
   * <code>optional bool supporting = 8;</code>
   */
  boolean getSupporting();

  /**
   * <code>optional .google.protobuf.Timestamp updatedAt = 9;</code>
   */
  boolean hasUpdatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp updatedAt = 9;</code>
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp updatedAt = 9;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();
}
