// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/api/igdb/igdbproto.proto

package proto;

/**
 * Protobuf type {@code proto.Platform}
 */
public final class Platform extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Platform)
    PlatformOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Platform.newBuilder() to construct.
  private Platform(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Platform() {
    abbreviation_ = "";
    alternativeName_ = "";
    category_ = 0;
    name_ = "";
    slug_ = "";
    summary_ = "";
    url_ = "";
    versions_ = java.util.Collections.emptyList();
    websites_ = java.util.Collections.emptyList();
    checksum_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Platform();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Igdbproto.internal_static_proto_Platform_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Igdbproto.internal_static_proto_Platform_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.Platform.class, proto.Platform.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int ABBREVIATION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object abbreviation_ = "";
  /**
   * <code>string abbreviation = 2;</code>
   * @return The abbreviation.
   */
  @java.lang.Override
  public java.lang.String getAbbreviation() {
    java.lang.Object ref = abbreviation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      abbreviation_ = s;
      return s;
    }
  }
  /**
   * <code>string abbreviation = 2;</code>
   * @return The bytes for abbreviation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAbbreviationBytes() {
    java.lang.Object ref = abbreviation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      abbreviation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALTERNATIVE_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alternativeName_ = "";
  /**
   * <code>string alternative_name = 3;</code>
   * @return The alternativeName.
   */
  @java.lang.Override
  public java.lang.String getAlternativeName() {
    java.lang.Object ref = alternativeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alternativeName_ = s;
      return s;
    }
  }
  /**
   * <code>string alternative_name = 3;</code>
   * @return The bytes for alternativeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlternativeNameBytes() {
    java.lang.Object ref = alternativeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alternativeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 4;
  private int category_ = 0;
  /**
   * <code>.proto.PlatformCategoryEnum category = 4;</code>
   * @return The enum numeric value on the wire for category.
   */
  @java.lang.Override public int getCategoryValue() {
    return category_;
  }
  /**
   * <code>.proto.PlatformCategoryEnum category = 4;</code>
   * @return The category.
   */
  @java.lang.Override public proto.PlatformCategoryEnum getCategory() {
    proto.PlatformCategoryEnum result = proto.PlatformCategoryEnum.forNumber(category_);
    return result == null ? proto.PlatformCategoryEnum.UNRECOGNIZED : result;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 5;</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return createdAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 5;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  public static final int GENERATION_FIELD_NUMBER = 6;
  private int generation_ = 0;
  /**
   * <code>int32 generation = 6;</code>
   * @return The generation.
   */
  @java.lang.Override
  public int getGeneration() {
    return generation_;
  }

  public static final int NAME_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 7;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 7;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORM_LOGO_FIELD_NUMBER = 8;
  private proto.PlatformLogo platformLogo_;
  /**
   * <code>.proto.PlatformLogo platform_logo = 8;</code>
   * @return Whether the platformLogo field is set.
   */
  @java.lang.Override
  public boolean hasPlatformLogo() {
    return platformLogo_ != null;
  }
  /**
   * <code>.proto.PlatformLogo platform_logo = 8;</code>
   * @return The platformLogo.
   */
  @java.lang.Override
  public proto.PlatformLogo getPlatformLogo() {
    return platformLogo_ == null ? proto.PlatformLogo.getDefaultInstance() : platformLogo_;
  }
  /**
   * <code>.proto.PlatformLogo platform_logo = 8;</code>
   */
  @java.lang.Override
  public proto.PlatformLogoOrBuilder getPlatformLogoOrBuilder() {
    return platformLogo_ == null ? proto.PlatformLogo.getDefaultInstance() : platformLogo_;
  }

  public static final int PLATFORM_FAMILY_FIELD_NUMBER = 9;
  private proto.PlatformFamily platformFamily_;
  /**
   * <code>.proto.PlatformFamily platform_family = 9;</code>
   * @return Whether the platformFamily field is set.
   */
  @java.lang.Override
  public boolean hasPlatformFamily() {
    return platformFamily_ != null;
  }
  /**
   * <code>.proto.PlatformFamily platform_family = 9;</code>
   * @return The platformFamily.
   */
  @java.lang.Override
  public proto.PlatformFamily getPlatformFamily() {
    return platformFamily_ == null ? proto.PlatformFamily.getDefaultInstance() : platformFamily_;
  }
  /**
   * <code>.proto.PlatformFamily platform_family = 9;</code>
   */
  @java.lang.Override
  public proto.PlatformFamilyOrBuilder getPlatformFamilyOrBuilder() {
    return platformFamily_ == null ? proto.PlatformFamily.getDefaultInstance() : platformFamily_;
  }

  public static final int SLUG_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object slug_ = "";
  /**
   * <code>string slug = 10;</code>
   * @return The slug.
   */
  @java.lang.Override
  public java.lang.String getSlug() {
    java.lang.Object ref = slug_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      slug_ = s;
      return s;
    }
  }
  /**
   * <code>string slug = 10;</code>
   * @return The bytes for slug.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSlugBytes() {
    java.lang.Object ref = slug_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      slug_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUMMARY_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object summary_ = "";
  /**
   * <code>string summary = 11;</code>
   * @return The summary.
   */
  @java.lang.Override
  public java.lang.String getSummary() {
    java.lang.Object ref = summary_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      summary_ = s;
      return s;
    }
  }
  /**
   * <code>string summary = 11;</code>
   * @return The bytes for summary.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSummaryBytes() {
    java.lang.Object ref = summary_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      summary_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 12;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <code>.google.protobuf.Timestamp updated_at = 12;</code>
   * @return Whether the updatedAt field is set.
   */
  @java.lang.Override
  public boolean hasUpdatedAt() {
    return updatedAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 12;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 12;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }

  public static final int URL_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object url_ = "";
  /**
   * <code>string url = 13;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>string url = 13;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSIONS_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private java.util.List<proto.PlatformVersion> versions_;
  /**
   * <code>repeated .proto.PlatformVersion versions = 14;</code>
   */
  @java.lang.Override
  public java.util.List<proto.PlatformVersion> getVersionsList() {
    return versions_;
  }
  /**
   * <code>repeated .proto.PlatformVersion versions = 14;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.PlatformVersionOrBuilder> 
      getVersionsOrBuilderList() {
    return versions_;
  }
  /**
   * <code>repeated .proto.PlatformVersion versions = 14;</code>
   */
  @java.lang.Override
  public int getVersionsCount() {
    return versions_.size();
  }
  /**
   * <code>repeated .proto.PlatformVersion versions = 14;</code>
   */
  @java.lang.Override
  public proto.PlatformVersion getVersions(int index) {
    return versions_.get(index);
  }
  /**
   * <code>repeated .proto.PlatformVersion versions = 14;</code>
   */
  @java.lang.Override
  public proto.PlatformVersionOrBuilder getVersionsOrBuilder(
      int index) {
    return versions_.get(index);
  }

  public static final int WEBSITES_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private java.util.List<proto.PlatformWebsite> websites_;
  /**
   * <code>repeated .proto.PlatformWebsite websites = 15;</code>
   */
  @java.lang.Override
  public java.util.List<proto.PlatformWebsite> getWebsitesList() {
    return websites_;
  }
  /**
   * <code>repeated .proto.PlatformWebsite websites = 15;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.PlatformWebsiteOrBuilder> 
      getWebsitesOrBuilderList() {
    return websites_;
  }
  /**
   * <code>repeated .proto.PlatformWebsite websites = 15;</code>
   */
  @java.lang.Override
  public int getWebsitesCount() {
    return websites_.size();
  }
  /**
   * <code>repeated .proto.PlatformWebsite websites = 15;</code>
   */
  @java.lang.Override
  public proto.PlatformWebsite getWebsites(int index) {
    return websites_.get(index);
  }
  /**
   * <code>repeated .proto.PlatformWebsite websites = 15;</code>
   */
  @java.lang.Override
  public proto.PlatformWebsiteOrBuilder getWebsitesOrBuilder(
      int index) {
    return websites_.get(index);
  }

  public static final int CHECKSUM_FIELD_NUMBER = 16;
  @SuppressWarnings("serial")
  private volatile java.lang.Object checksum_ = "";
  /**
   * <code>string checksum = 16;</code>
   * @return The checksum.
   */
  @java.lang.Override
  public java.lang.String getChecksum() {
    java.lang.Object ref = checksum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      checksum_ = s;
      return s;
    }
  }
  /**
   * <code>string checksum = 16;</code>
   * @return The bytes for checksum.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChecksumBytes() {
    java.lang.Object ref = checksum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      checksum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static proto.Platform parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Platform parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Platform parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Platform parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Platform parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Platform parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Platform parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.Platform parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.Platform parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.Platform parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.Platform parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.Platform parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.Platform prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Platform}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Platform)
      proto.PlatformOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Igdbproto.internal_static_proto_Platform_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Igdbproto.internal_static_proto_Platform_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Platform.class, proto.Platform.Builder.class);
    }

    // Construct using proto.Platform.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      abbreviation_ = "";
      alternativeName_ = "";
      category_ = 0;
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      generation_ = 0;
      name_ = "";
      platformLogo_ = null;
      if (platformLogoBuilder_ != null) {
        platformLogoBuilder_.dispose();
        platformLogoBuilder_ = null;
      }
      platformFamily_ = null;
      if (platformFamilyBuilder_ != null) {
        platformFamilyBuilder_.dispose();
        platformFamilyBuilder_ = null;
      }
      slug_ = "";
      summary_ = "";
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      url_ = "";
      if (versionsBuilder_ == null) {
        versions_ = java.util.Collections.emptyList();
      } else {
        versions_ = null;
        versionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00002000);
      if (websitesBuilder_ == null) {
        websites_ = java.util.Collections.emptyList();
      } else {
        websites_ = null;
        websitesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00004000);
      checksum_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Igdbproto.internal_static_proto_Platform_descriptor;
    }

    @java.lang.Override
    public proto.Platform getDefaultInstanceForType() {
      return proto.Platform.getDefaultInstance();
    }

    @java.lang.Override
    public proto.Platform build() {
      proto.Platform result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.Platform buildPartial() {
      proto.Platform result = new proto.Platform(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(proto.Platform result) {
      if (versionsBuilder_ == null) {
        if (((bitField0_ & 0x00002000) != 0)) {
          versions_ = java.util.Collections.unmodifiableList(versions_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.versions_ = versions_;
      } else {
        result.versions_ = versionsBuilder_.build();
      }
      if (websitesBuilder_ == null) {
        if (((bitField0_ & 0x00004000) != 0)) {
          websites_ = java.util.Collections.unmodifiableList(websites_);
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.websites_ = websites_;
      } else {
        result.websites_ = websitesBuilder_.build();
      }
    }

    private void buildPartial0(proto.Platform result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.abbreviation_ = abbreviation_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.alternativeName_ = alternativeName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.category_ = category_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.generation_ = generation_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.platformLogo_ = platformLogoBuilder_ == null
            ? platformLogo_
            : platformLogoBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.platformFamily_ = platformFamilyBuilder_ == null
            ? platformFamily_
            : platformFamilyBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.slug_ = slug_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.summary_ = summary_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.updatedAt_ = updatedAtBuilder_ == null
            ? updatedAt_
            : updatedAtBuilder_.build();
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.url_ = url_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.checksum_ = checksum_;
      }
    }

    private int bitField0_;

    private long id_ ;
    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>uint64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object abbreviation_ = "";
    /**
     * <code>string abbreviation = 2;</code>
     * @return The abbreviation.
     */
    public java.lang.String getAbbreviation() {
      java.lang.Object ref = abbreviation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        abbreviation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string abbreviation = 2;</code>
     * @return The bytes for abbreviation.
     */
    public com.google.protobuf.ByteString
        getAbbreviationBytes() {
      java.lang.Object ref = abbreviation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        abbreviation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string abbreviation = 2;</code>
     * @param value The abbreviation to set.
     * @return This builder for chaining.
     */
    public Builder setAbbreviation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      abbreviation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string abbreviation = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAbbreviation() {
      abbreviation_ = getDefaultInstance().getAbbreviation();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string abbreviation = 2;</code>
     * @param value The bytes for abbreviation to set.
     * @return This builder for chaining.
     */
    public Builder setAbbreviationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      abbreviation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object alternativeName_ = "";
    /**
     * <code>string alternative_name = 3;</code>
     * @return The alternativeName.
     */
    public java.lang.String getAlternativeName() {
      java.lang.Object ref = alternativeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alternativeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alternative_name = 3;</code>
     * @return The bytes for alternativeName.
     */
    public com.google.protobuf.ByteString
        getAlternativeNameBytes() {
      java.lang.Object ref = alternativeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alternativeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alternative_name = 3;</code>
     * @param value The alternativeName to set.
     * @return This builder for chaining.
     */
    public Builder setAlternativeName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alternativeName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string alternative_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlternativeName() {
      alternativeName_ = getDefaultInstance().getAlternativeName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string alternative_name = 3;</code>
     * @param value The bytes for alternativeName to set.
     * @return This builder for chaining.
     */
    public Builder setAlternativeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alternativeName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int category_ = 0;
    /**
     * <code>.proto.PlatformCategoryEnum category = 4;</code>
     * @return The enum numeric value on the wire for category.
     */
    @java.lang.Override public int getCategoryValue() {
      return category_;
    }
    /**
     * <code>.proto.PlatformCategoryEnum category = 4;</code>
     * @param value The enum numeric value on the wire for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryValue(int value) {
      category_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PlatformCategoryEnum category = 4;</code>
     * @return The category.
     */
    @java.lang.Override
    public proto.PlatformCategoryEnum getCategory() {
      proto.PlatformCategoryEnum result = proto.PlatformCategoryEnum.forNumber(category_);
      return result == null ? proto.PlatformCategoryEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.proto.PlatformCategoryEnum category = 4;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(proto.PlatformCategoryEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      category_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PlatformCategoryEnum category = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      bitField0_ = (bitField0_ & ~0x00000008);
      category_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 5;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5;</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000010);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private int generation_ ;
    /**
     * <code>int32 generation = 6;</code>
     * @return The generation.
     */
    @java.lang.Override
    public int getGeneration() {
      return generation_;
    }
    /**
     * <code>int32 generation = 6;</code>
     * @param value The generation to set.
     * @return This builder for chaining.
     */
    public Builder setGeneration(int value) {

      generation_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 generation = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGeneration() {
      bitField0_ = (bitField0_ & ~0x00000020);
      generation_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 7;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 7;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 7;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 7;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private proto.PlatformLogo platformLogo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.PlatformLogo, proto.PlatformLogo.Builder, proto.PlatformLogoOrBuilder> platformLogoBuilder_;
    /**
     * <code>.proto.PlatformLogo platform_logo = 8;</code>
     * @return Whether the platformLogo field is set.
     */
    public boolean hasPlatformLogo() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.proto.PlatformLogo platform_logo = 8;</code>
     * @return The platformLogo.
     */
    public proto.PlatformLogo getPlatformLogo() {
      if (platformLogoBuilder_ == null) {
        return platformLogo_ == null ? proto.PlatformLogo.getDefaultInstance() : platformLogo_;
      } else {
        return platformLogoBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.PlatformLogo platform_logo = 8;</code>
     */
    public Builder setPlatformLogo(proto.PlatformLogo value) {
      if (platformLogoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        platformLogo_ = value;
      } else {
        platformLogoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PlatformLogo platform_logo = 8;</code>
     */
    public Builder setPlatformLogo(
        proto.PlatformLogo.Builder builderForValue) {
      if (platformLogoBuilder_ == null) {
        platformLogo_ = builderForValue.build();
      } else {
        platformLogoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PlatformLogo platform_logo = 8;</code>
     */
    public Builder mergePlatformLogo(proto.PlatformLogo value) {
      if (platformLogoBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          platformLogo_ != null &&
          platformLogo_ != proto.PlatformLogo.getDefaultInstance()) {
          getPlatformLogoBuilder().mergeFrom(value);
        } else {
          platformLogo_ = value;
        }
      } else {
        platformLogoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PlatformLogo platform_logo = 8;</code>
     */
    public Builder clearPlatformLogo() {
      bitField0_ = (bitField0_ & ~0x00000080);
      platformLogo_ = null;
      if (platformLogoBuilder_ != null) {
        platformLogoBuilder_.dispose();
        platformLogoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PlatformLogo platform_logo = 8;</code>
     */
    public proto.PlatformLogo.Builder getPlatformLogoBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getPlatformLogoFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.PlatformLogo platform_logo = 8;</code>
     */
    public proto.PlatformLogoOrBuilder getPlatformLogoOrBuilder() {
      if (platformLogoBuilder_ != null) {
        return platformLogoBuilder_.getMessageOrBuilder();
      } else {
        return platformLogo_ == null ?
            proto.PlatformLogo.getDefaultInstance() : platformLogo_;
      }
    }
    /**
     * <code>.proto.PlatformLogo platform_logo = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.PlatformLogo, proto.PlatformLogo.Builder, proto.PlatformLogoOrBuilder> 
        getPlatformLogoFieldBuilder() {
      if (platformLogoBuilder_ == null) {
        platformLogoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.PlatformLogo, proto.PlatformLogo.Builder, proto.PlatformLogoOrBuilder>(
                getPlatformLogo(),
                getParentForChildren(),
                isClean());
        platformLogo_ = null;
      }
      return platformLogoBuilder_;
    }

    private proto.PlatformFamily platformFamily_;
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.PlatformFamily, proto.PlatformFamily.Builder, proto.PlatformFamilyOrBuilder> platformFamilyBuilder_;
    /**
     * <code>.proto.PlatformFamily platform_family = 9;</code>
     * @return Whether the platformFamily field is set.
     */
    public boolean hasPlatformFamily() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.proto.PlatformFamily platform_family = 9;</code>
     * @return The platformFamily.
     */
    public proto.PlatformFamily getPlatformFamily() {
      if (platformFamilyBuilder_ == null) {
        return platformFamily_ == null ? proto.PlatformFamily.getDefaultInstance() : platformFamily_;
      } else {
        return platformFamilyBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.PlatformFamily platform_family = 9;</code>
     */
    public Builder setPlatformFamily(proto.PlatformFamily value) {
      if (platformFamilyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        platformFamily_ = value;
      } else {
        platformFamilyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PlatformFamily platform_family = 9;</code>
     */
    public Builder setPlatformFamily(
        proto.PlatformFamily.Builder builderForValue) {
      if (platformFamilyBuilder_ == null) {
        platformFamily_ = builderForValue.build();
      } else {
        platformFamilyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PlatformFamily platform_family = 9;</code>
     */
    public Builder mergePlatformFamily(proto.PlatformFamily value) {
      if (platformFamilyBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          platformFamily_ != null &&
          platformFamily_ != proto.PlatformFamily.getDefaultInstance()) {
          getPlatformFamilyBuilder().mergeFrom(value);
        } else {
          platformFamily_ = value;
        }
      } else {
        platformFamilyBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PlatformFamily platform_family = 9;</code>
     */
    public Builder clearPlatformFamily() {
      bitField0_ = (bitField0_ & ~0x00000100);
      platformFamily_ = null;
      if (platformFamilyBuilder_ != null) {
        platformFamilyBuilder_.dispose();
        platformFamilyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.PlatformFamily platform_family = 9;</code>
     */
    public proto.PlatformFamily.Builder getPlatformFamilyBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getPlatformFamilyFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.PlatformFamily platform_family = 9;</code>
     */
    public proto.PlatformFamilyOrBuilder getPlatformFamilyOrBuilder() {
      if (platformFamilyBuilder_ != null) {
        return platformFamilyBuilder_.getMessageOrBuilder();
      } else {
        return platformFamily_ == null ?
            proto.PlatformFamily.getDefaultInstance() : platformFamily_;
      }
    }
    /**
     * <code>.proto.PlatformFamily platform_family = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.PlatformFamily, proto.PlatformFamily.Builder, proto.PlatformFamilyOrBuilder> 
        getPlatformFamilyFieldBuilder() {
      if (platformFamilyBuilder_ == null) {
        platformFamilyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.PlatformFamily, proto.PlatformFamily.Builder, proto.PlatformFamilyOrBuilder>(
                getPlatformFamily(),
                getParentForChildren(),
                isClean());
        platformFamily_ = null;
      }
      return platformFamilyBuilder_;
    }

    private java.lang.Object slug_ = "";
    /**
     * <code>string slug = 10;</code>
     * @return The slug.
     */
    public java.lang.String getSlug() {
      java.lang.Object ref = slug_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        slug_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string slug = 10;</code>
     * @return The bytes for slug.
     */
    public com.google.protobuf.ByteString
        getSlugBytes() {
      java.lang.Object ref = slug_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slug_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string slug = 10;</code>
     * @param value The slug to set.
     * @return This builder for chaining.
     */
    public Builder setSlug(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      slug_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string slug = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlug() {
      slug_ = getDefaultInstance().getSlug();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string slug = 10;</code>
     * @param value The bytes for slug to set.
     * @return This builder for chaining.
     */
    public Builder setSlugBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      slug_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object summary_ = "";
    /**
     * <code>string summary = 11;</code>
     * @return The summary.
     */
    public java.lang.String getSummary() {
      java.lang.Object ref = summary_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        summary_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string summary = 11;</code>
     * @return The bytes for summary.
     */
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      java.lang.Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string summary = 11;</code>
     * @param value The summary to set.
     * @return This builder for chaining.
     */
    public Builder setSummary(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      summary_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string summary = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSummary() {
      summary_ = getDefaultInstance().getSummary();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string summary = 11;</code>
     * @param value The bytes for summary to set.
     * @return This builder for chaining.
     */
    public Builder setSummaryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      summary_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp updatedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 12;</code>
     * @return Whether the updatedAt field is set.
     */
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 12;</code>
     * @return The updatedAt.
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      } else {
        return updatedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 12;</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updatedAt_ = value;
      } else {
        updatedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 12;</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = builderForValue.build();
      } else {
        updatedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 12;</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
          updatedAt_ != null &&
          updatedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getUpdatedAtBuilder().mergeFrom(value);
        } else {
          updatedAt_ = value;
        }
      } else {
        updatedAtBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 12;</code>
     */
    public Builder clearUpdatedAt() {
      bitField0_ = (bitField0_ & ~0x00000800);
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 12;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 12;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      if (updatedAtBuilder_ != null) {
        return updatedAtBuilder_.getMessageOrBuilder();
      } else {
        return updatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdatedAtFieldBuilder() {
      if (updatedAtBuilder_ == null) {
        updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedAt(),
                getParentForChildren(),
                isClean());
        updatedAt_ = null;
      }
      return updatedAtBuilder_;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>string url = 13;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string url = 13;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string url = 13;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      url_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string url = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      url_ = getDefaultInstance().getUrl();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string url = 13;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      url_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private java.util.List<proto.PlatformVersion> versions_ =
      java.util.Collections.emptyList();
    private void ensureVersionsIsMutable() {
      if (!((bitField0_ & 0x00002000) != 0)) {
        versions_ = new java.util.ArrayList<proto.PlatformVersion>(versions_);
        bitField0_ |= 0x00002000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.PlatformVersion, proto.PlatformVersion.Builder, proto.PlatformVersionOrBuilder> versionsBuilder_;

    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public java.util.List<proto.PlatformVersion> getVersionsList() {
      if (versionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(versions_);
      } else {
        return versionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public int getVersionsCount() {
      if (versionsBuilder_ == null) {
        return versions_.size();
      } else {
        return versionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public proto.PlatformVersion getVersions(int index) {
      if (versionsBuilder_ == null) {
        return versions_.get(index);
      } else {
        return versionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public Builder setVersions(
        int index, proto.PlatformVersion value) {
      if (versionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVersionsIsMutable();
        versions_.set(index, value);
        onChanged();
      } else {
        versionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public Builder setVersions(
        int index, proto.PlatformVersion.Builder builderForValue) {
      if (versionsBuilder_ == null) {
        ensureVersionsIsMutable();
        versions_.set(index, builderForValue.build());
        onChanged();
      } else {
        versionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public Builder addVersions(proto.PlatformVersion value) {
      if (versionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVersionsIsMutable();
        versions_.add(value);
        onChanged();
      } else {
        versionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public Builder addVersions(
        int index, proto.PlatformVersion value) {
      if (versionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVersionsIsMutable();
        versions_.add(index, value);
        onChanged();
      } else {
        versionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public Builder addVersions(
        proto.PlatformVersion.Builder builderForValue) {
      if (versionsBuilder_ == null) {
        ensureVersionsIsMutable();
        versions_.add(builderForValue.build());
        onChanged();
      } else {
        versionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public Builder addVersions(
        int index, proto.PlatformVersion.Builder builderForValue) {
      if (versionsBuilder_ == null) {
        ensureVersionsIsMutable();
        versions_.add(index, builderForValue.build());
        onChanged();
      } else {
        versionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public Builder addAllVersions(
        java.lang.Iterable<? extends proto.PlatformVersion> values) {
      if (versionsBuilder_ == null) {
        ensureVersionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, versions_);
        onChanged();
      } else {
        versionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public Builder clearVersions() {
      if (versionsBuilder_ == null) {
        versions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
      } else {
        versionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public Builder removeVersions(int index) {
      if (versionsBuilder_ == null) {
        ensureVersionsIsMutable();
        versions_.remove(index);
        onChanged();
      } else {
        versionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public proto.PlatformVersion.Builder getVersionsBuilder(
        int index) {
      return getVersionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public proto.PlatformVersionOrBuilder getVersionsOrBuilder(
        int index) {
      if (versionsBuilder_ == null) {
        return versions_.get(index);  } else {
        return versionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public java.util.List<? extends proto.PlatformVersionOrBuilder> 
         getVersionsOrBuilderList() {
      if (versionsBuilder_ != null) {
        return versionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(versions_);
      }
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public proto.PlatformVersion.Builder addVersionsBuilder() {
      return getVersionsFieldBuilder().addBuilder(
          proto.PlatformVersion.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public proto.PlatformVersion.Builder addVersionsBuilder(
        int index) {
      return getVersionsFieldBuilder().addBuilder(
          index, proto.PlatformVersion.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.PlatformVersion versions = 14;</code>
     */
    public java.util.List<proto.PlatformVersion.Builder> 
         getVersionsBuilderList() {
      return getVersionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.PlatformVersion, proto.PlatformVersion.Builder, proto.PlatformVersionOrBuilder> 
        getVersionsFieldBuilder() {
      if (versionsBuilder_ == null) {
        versionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.PlatformVersion, proto.PlatformVersion.Builder, proto.PlatformVersionOrBuilder>(
                versions_,
                ((bitField0_ & 0x00002000) != 0),
                getParentForChildren(),
                isClean());
        versions_ = null;
      }
      return versionsBuilder_;
    }

    private java.util.List<proto.PlatformWebsite> websites_ =
      java.util.Collections.emptyList();
    private void ensureWebsitesIsMutable() {
      if (!((bitField0_ & 0x00004000) != 0)) {
        websites_ = new java.util.ArrayList<proto.PlatformWebsite>(websites_);
        bitField0_ |= 0x00004000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.PlatformWebsite, proto.PlatformWebsite.Builder, proto.PlatformWebsiteOrBuilder> websitesBuilder_;

    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public java.util.List<proto.PlatformWebsite> getWebsitesList() {
      if (websitesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(websites_);
      } else {
        return websitesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public int getWebsitesCount() {
      if (websitesBuilder_ == null) {
        return websites_.size();
      } else {
        return websitesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public proto.PlatformWebsite getWebsites(int index) {
      if (websitesBuilder_ == null) {
        return websites_.get(index);
      } else {
        return websitesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public Builder setWebsites(
        int index, proto.PlatformWebsite value) {
      if (websitesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWebsitesIsMutable();
        websites_.set(index, value);
        onChanged();
      } else {
        websitesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public Builder setWebsites(
        int index, proto.PlatformWebsite.Builder builderForValue) {
      if (websitesBuilder_ == null) {
        ensureWebsitesIsMutable();
        websites_.set(index, builderForValue.build());
        onChanged();
      } else {
        websitesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public Builder addWebsites(proto.PlatformWebsite value) {
      if (websitesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWebsitesIsMutable();
        websites_.add(value);
        onChanged();
      } else {
        websitesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public Builder addWebsites(
        int index, proto.PlatformWebsite value) {
      if (websitesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWebsitesIsMutable();
        websites_.add(index, value);
        onChanged();
      } else {
        websitesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public Builder addWebsites(
        proto.PlatformWebsite.Builder builderForValue) {
      if (websitesBuilder_ == null) {
        ensureWebsitesIsMutable();
        websites_.add(builderForValue.build());
        onChanged();
      } else {
        websitesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public Builder addWebsites(
        int index, proto.PlatformWebsite.Builder builderForValue) {
      if (websitesBuilder_ == null) {
        ensureWebsitesIsMutable();
        websites_.add(index, builderForValue.build());
        onChanged();
      } else {
        websitesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public Builder addAllWebsites(
        java.lang.Iterable<? extends proto.PlatformWebsite> values) {
      if (websitesBuilder_ == null) {
        ensureWebsitesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, websites_);
        onChanged();
      } else {
        websitesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public Builder clearWebsites() {
      if (websitesBuilder_ == null) {
        websites_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
      } else {
        websitesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public Builder removeWebsites(int index) {
      if (websitesBuilder_ == null) {
        ensureWebsitesIsMutable();
        websites_.remove(index);
        onChanged();
      } else {
        websitesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public proto.PlatformWebsite.Builder getWebsitesBuilder(
        int index) {
      return getWebsitesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public proto.PlatformWebsiteOrBuilder getWebsitesOrBuilder(
        int index) {
      if (websitesBuilder_ == null) {
        return websites_.get(index);  } else {
        return websitesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public java.util.List<? extends proto.PlatformWebsiteOrBuilder> 
         getWebsitesOrBuilderList() {
      if (websitesBuilder_ != null) {
        return websitesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(websites_);
      }
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public proto.PlatformWebsite.Builder addWebsitesBuilder() {
      return getWebsitesFieldBuilder().addBuilder(
          proto.PlatformWebsite.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public proto.PlatformWebsite.Builder addWebsitesBuilder(
        int index) {
      return getWebsitesFieldBuilder().addBuilder(
          index, proto.PlatformWebsite.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.PlatformWebsite websites = 15;</code>
     */
    public java.util.List<proto.PlatformWebsite.Builder> 
         getWebsitesBuilderList() {
      return getWebsitesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.PlatformWebsite, proto.PlatformWebsite.Builder, proto.PlatformWebsiteOrBuilder> 
        getWebsitesFieldBuilder() {
      if (websitesBuilder_ == null) {
        websitesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.PlatformWebsite, proto.PlatformWebsite.Builder, proto.PlatformWebsiteOrBuilder>(
                websites_,
                ((bitField0_ & 0x00004000) != 0),
                getParentForChildren(),
                isClean());
        websites_ = null;
      }
      return websitesBuilder_;
    }

    private java.lang.Object checksum_ = "";
    /**
     * <code>string checksum = 16;</code>
     * @return The checksum.
     */
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checksum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string checksum = 16;</code>
     * @return The bytes for checksum.
     */
    public com.google.protobuf.ByteString
        getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string checksum = 16;</code>
     * @param value The checksum to set.
     * @return This builder for chaining.
     */
    public Builder setChecksum(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      checksum_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>string checksum = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearChecksum() {
      checksum_ = getDefaultInstance().getChecksum();
      bitField0_ = (bitField0_ & ~0x00008000);
      onChanged();
      return this;
    }
    /**
     * <code>string checksum = 16;</code>
     * @param value The bytes for checksum to set.
     * @return This builder for chaining.
     */
    public Builder setChecksumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      checksum_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.Platform)
  }

  // @@protoc_insertion_point(class_scope:proto.Platform)
  private static final proto.Platform DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.Platform();
  }

  public static proto.Platform getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Platform>
      PARSER = new com.google.protobuf.AbstractParser<Platform>() {
    @java.lang.Override
    public Platform parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Platform> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Platform> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.Platform getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

