// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/api/igdb/igdbproto.proto

package proto;

public interface PlatformFamilyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PlatformFamily)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string slug = 3;</code>
   */
  java.lang.String getSlug();
  /**
   * <code>string slug = 3;</code>
   */
  com.google.protobuf.ByteString
      getSlugBytes();

  /**
   * <code>string checksum = 4;</code>
   */
  java.lang.String getChecksum();
  /**
   * <code>string checksum = 4;</code>
   */
  com.google.protobuf.ByteString
      getChecksumBytes();
}
