// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/api/igdb/igdbproto.proto

package proto;

/**
 * Protobuf type {@code proto.ReleaseDateResult}
 */
public final class ReleaseDateResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.ReleaseDateResult)
    ReleaseDateResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReleaseDateResult.newBuilder() to construct.
  private ReleaseDateResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReleaseDateResult() {
    releasedates_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReleaseDateResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Igdbproto.internal_static_proto_ReleaseDateResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Igdbproto.internal_static_proto_ReleaseDateResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.ReleaseDateResult.class, proto.ReleaseDateResult.Builder.class);
  }

  public static final int RELEASEDATES_FIELD_NUMBER = 1;
  private java.util.List<proto.ReleaseDate> releasedates_;
  /**
   * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
   */
  @java.lang.Override
  public java.util.List<proto.ReleaseDate> getReleasedatesList() {
    return releasedates_;
  }
  /**
   * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.ReleaseDateOrBuilder> 
      getReleasedatesOrBuilderList() {
    return releasedates_;
  }
  /**
   * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
   */
  @java.lang.Override
  public int getReleasedatesCount() {
    return releasedates_.size();
  }
  /**
   * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
   */
  @java.lang.Override
  public proto.ReleaseDate getReleasedates(int index) {
    return releasedates_.get(index);
  }
  /**
   * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
   */
  @java.lang.Override
  public proto.ReleaseDateOrBuilder getReleasedatesOrBuilder(
      int index) {
    return releasedates_.get(index);
  }

  public static proto.ReleaseDateResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.ReleaseDateResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.ReleaseDateResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.ReleaseDateResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.ReleaseDateResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.ReleaseDateResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.ReleaseDateResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.ReleaseDateResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.ReleaseDateResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.ReleaseDateResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.ReleaseDateResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.ReleaseDateResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.ReleaseDateResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.ReleaseDateResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.ReleaseDateResult)
      proto.ReleaseDateResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Igdbproto.internal_static_proto_ReleaseDateResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Igdbproto.internal_static_proto_ReleaseDateResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ReleaseDateResult.class, proto.ReleaseDateResult.Builder.class);
    }

    // Construct using proto.ReleaseDateResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (releasedatesBuilder_ == null) {
        releasedates_ = java.util.Collections.emptyList();
      } else {
        releasedates_ = null;
        releasedatesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Igdbproto.internal_static_proto_ReleaseDateResult_descriptor;
    }

    @java.lang.Override
    public proto.ReleaseDateResult getDefaultInstanceForType() {
      return proto.ReleaseDateResult.getDefaultInstance();
    }

    @java.lang.Override
    public proto.ReleaseDateResult build() {
      proto.ReleaseDateResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.ReleaseDateResult buildPartial() {
      proto.ReleaseDateResult result = new proto.ReleaseDateResult(this);
      int from_bitField0_ = bitField0_;
      if (releasedatesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          releasedates_ = java.util.Collections.unmodifiableList(releasedates_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.releasedates_ = releasedates_;
      } else {
        result.releasedates_ = releasedatesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private java.util.List<proto.ReleaseDate> releasedates_ =
      java.util.Collections.emptyList();
    private void ensureReleasedatesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        releasedates_ = new java.util.ArrayList<proto.ReleaseDate>(releasedates_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.ReleaseDate, proto.ReleaseDate.Builder, proto.ReleaseDateOrBuilder> releasedatesBuilder_;

    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public java.util.List<proto.ReleaseDate> getReleasedatesList() {
      if (releasedatesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(releasedates_);
      } else {
        return releasedatesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public int getReleasedatesCount() {
      if (releasedatesBuilder_ == null) {
        return releasedates_.size();
      } else {
        return releasedatesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public proto.ReleaseDate getReleasedates(int index) {
      if (releasedatesBuilder_ == null) {
        return releasedates_.get(index);
      } else {
        return releasedatesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public Builder setReleasedates(
        int index, proto.ReleaseDate value) {
      if (releasedatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReleasedatesIsMutable();
        releasedates_.set(index, value);
        onChanged();
      } else {
        releasedatesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public Builder setReleasedates(
        int index, proto.ReleaseDate.Builder builderForValue) {
      if (releasedatesBuilder_ == null) {
        ensureReleasedatesIsMutable();
        releasedates_.set(index, builderForValue.build());
        onChanged();
      } else {
        releasedatesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public Builder addReleasedates(proto.ReleaseDate value) {
      if (releasedatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReleasedatesIsMutable();
        releasedates_.add(value);
        onChanged();
      } else {
        releasedatesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public Builder addReleasedates(
        int index, proto.ReleaseDate value) {
      if (releasedatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReleasedatesIsMutable();
        releasedates_.add(index, value);
        onChanged();
      } else {
        releasedatesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public Builder addReleasedates(
        proto.ReleaseDate.Builder builderForValue) {
      if (releasedatesBuilder_ == null) {
        ensureReleasedatesIsMutable();
        releasedates_.add(builderForValue.build());
        onChanged();
      } else {
        releasedatesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public Builder addReleasedates(
        int index, proto.ReleaseDate.Builder builderForValue) {
      if (releasedatesBuilder_ == null) {
        ensureReleasedatesIsMutable();
        releasedates_.add(index, builderForValue.build());
        onChanged();
      } else {
        releasedatesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public Builder addAllReleasedates(
        java.lang.Iterable<? extends proto.ReleaseDate> values) {
      if (releasedatesBuilder_ == null) {
        ensureReleasedatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, releasedates_);
        onChanged();
      } else {
        releasedatesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public Builder clearReleasedates() {
      if (releasedatesBuilder_ == null) {
        releasedates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        releasedatesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public Builder removeReleasedates(int index) {
      if (releasedatesBuilder_ == null) {
        ensureReleasedatesIsMutable();
        releasedates_.remove(index);
        onChanged();
      } else {
        releasedatesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public proto.ReleaseDate.Builder getReleasedatesBuilder(
        int index) {
      return getReleasedatesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public proto.ReleaseDateOrBuilder getReleasedatesOrBuilder(
        int index) {
      if (releasedatesBuilder_ == null) {
        return releasedates_.get(index);  } else {
        return releasedatesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public java.util.List<? extends proto.ReleaseDateOrBuilder> 
         getReleasedatesOrBuilderList() {
      if (releasedatesBuilder_ != null) {
        return releasedatesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(releasedates_);
      }
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public proto.ReleaseDate.Builder addReleasedatesBuilder() {
      return getReleasedatesFieldBuilder().addBuilder(
          proto.ReleaseDate.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public proto.ReleaseDate.Builder addReleasedatesBuilder(
        int index) {
      return getReleasedatesFieldBuilder().addBuilder(
          index, proto.ReleaseDate.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.ReleaseDate releasedates = 1;</code>
     */
    public java.util.List<proto.ReleaseDate.Builder> 
         getReleasedatesBuilderList() {
      return getReleasedatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.ReleaseDate, proto.ReleaseDate.Builder, proto.ReleaseDateOrBuilder> 
        getReleasedatesFieldBuilder() {
      if (releasedatesBuilder_ == null) {
        releasedatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.ReleaseDate, proto.ReleaseDate.Builder, proto.ReleaseDateOrBuilder>(
                releasedates_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        releasedates_ = null;
      }
      return releasedatesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.ReleaseDateResult)
  }

  // @@protoc_insertion_point(class_scope:proto.ReleaseDateResult)
  private static final proto.ReleaseDateResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.ReleaseDateResult();
  }

  public static proto.ReleaseDateResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReleaseDateResult>
      PARSER = new com.google.protobuf.AbstractParser<ReleaseDateResult>() {
    @java.lang.Override
    public ReleaseDateResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReleaseDateResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReleaseDateResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.ReleaseDateResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

