// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/api/igdb/igdbproto.proto

package proto;

public interface ReleaseDateStatusResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ReleaseDateStatusResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.ReleaseDateStatus releasedatestatuses = 1;</code>
   */
  java.util.List<proto.ReleaseDateStatus> 
      getReleasedatestatusesList();
  /**
   * <code>repeated .proto.ReleaseDateStatus releasedatestatuses = 1;</code>
   */
  proto.ReleaseDateStatus getReleasedatestatuses(int index);
  /**
   * <code>repeated .proto.ReleaseDateStatus releasedatestatuses = 1;</code>
   */
  int getReleasedatestatusesCount();
  /**
   * <code>repeated .proto.ReleaseDateStatus releasedatestatuses = 1;</code>
   */
  java.util.List<? extends proto.ReleaseDateStatusOrBuilder> 
      getReleasedatestatusesOrBuilderList();
  /**
   * <code>repeated .proto.ReleaseDateStatus releasedatestatuses = 1;</code>
   */
  proto.ReleaseDateStatusOrBuilder getReleasedatestatusesOrBuilder(
      int index);
}
