// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/api/igdb/igdbproto.proto

package proto;

/**
 * Protobuf type {@code proto.SearchResult}
 */
public  final class SearchResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.SearchResult)
    SearchResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchResult.newBuilder() to construct.
  private SearchResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchResult() {
    searches_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Igdbproto.internal_static_proto_SearchResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Igdbproto.internal_static_proto_SearchResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.SearchResult.class, proto.SearchResult.Builder.class);
  }

  public static final int SEARCHES_FIELD_NUMBER = 1;
  private java.util.List<proto.Search> searches_;
  /**
   * <code>repeated .proto.Search searches = 1;</code>
   */
  public java.util.List<proto.Search> getSearchesList() {
    return searches_;
  }
  /**
   * <code>repeated .proto.Search searches = 1;</code>
   */
  public java.util.List<? extends proto.SearchOrBuilder> 
      getSearchesOrBuilderList() {
    return searches_;
  }
  /**
   * <code>repeated .proto.Search searches = 1;</code>
   */
  public int getSearchesCount() {
    return searches_.size();
  }
  /**
   * <code>repeated .proto.Search searches = 1;</code>
   */
  public proto.Search getSearches(int index) {
    return searches_.get(index);
  }
  /**
   * <code>repeated .proto.Search searches = 1;</code>
   */
  public proto.SearchOrBuilder getSearchesOrBuilder(
      int index) {
    return searches_.get(index);
  }

  public static proto.SearchResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.SearchResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.SearchResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.SearchResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.SearchResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.SearchResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.SearchResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.SearchResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.SearchResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.SearchResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.SearchResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.SearchResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.SearchResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.SearchResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.SearchResult)
      proto.SearchResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Igdbproto.internal_static_proto_SearchResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Igdbproto.internal_static_proto_SearchResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SearchResult.class, proto.SearchResult.Builder.class);
    }

    // Construct using proto.SearchResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSearchesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (searchesBuilder_ == null) {
        searches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        searchesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Igdbproto.internal_static_proto_SearchResult_descriptor;
    }

    @java.lang.Override
    public proto.SearchResult getDefaultInstanceForType() {
      return proto.SearchResult.getDefaultInstance();
    }

    @java.lang.Override
    public proto.SearchResult build() {
      proto.SearchResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.SearchResult buildPartial() {
      proto.SearchResult result = new proto.SearchResult(this);
      int from_bitField0_ = bitField0_;
      if (searchesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          searches_ = java.util.Collections.unmodifiableList(searches_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.searches_ = searches_;
      } else {
        result.searches_ = searchesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private java.util.List<proto.Search> searches_ =
      java.util.Collections.emptyList();
    private void ensureSearchesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        searches_ = new java.util.ArrayList<proto.Search>(searches_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Search, proto.Search.Builder, proto.SearchOrBuilder> searchesBuilder_;

    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public java.util.List<proto.Search> getSearchesList() {
      if (searchesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(searches_);
      } else {
        return searchesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public int getSearchesCount() {
      if (searchesBuilder_ == null) {
        return searches_.size();
      } else {
        return searchesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public proto.Search getSearches(int index) {
      if (searchesBuilder_ == null) {
        return searches_.get(index);
      } else {
        return searchesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public Builder setSearches(
        int index, proto.Search value) {
      if (searchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSearchesIsMutable();
        searches_.set(index, value);
        onChanged();
      } else {
        searchesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public Builder setSearches(
        int index, proto.Search.Builder builderForValue) {
      if (searchesBuilder_ == null) {
        ensureSearchesIsMutable();
        searches_.set(index, builderForValue.build());
        onChanged();
      } else {
        searchesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public Builder addSearches(proto.Search value) {
      if (searchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSearchesIsMutable();
        searches_.add(value);
        onChanged();
      } else {
        searchesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public Builder addSearches(
        int index, proto.Search value) {
      if (searchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSearchesIsMutable();
        searches_.add(index, value);
        onChanged();
      } else {
        searchesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public Builder addSearches(
        proto.Search.Builder builderForValue) {
      if (searchesBuilder_ == null) {
        ensureSearchesIsMutable();
        searches_.add(builderForValue.build());
        onChanged();
      } else {
        searchesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public Builder addSearches(
        int index, proto.Search.Builder builderForValue) {
      if (searchesBuilder_ == null) {
        ensureSearchesIsMutable();
        searches_.add(index, builderForValue.build());
        onChanged();
      } else {
        searchesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public Builder addAllSearches(
        java.lang.Iterable<? extends proto.Search> values) {
      if (searchesBuilder_ == null) {
        ensureSearchesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, searches_);
        onChanged();
      } else {
        searchesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public Builder clearSearches() {
      if (searchesBuilder_ == null) {
        searches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        searchesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public Builder removeSearches(int index) {
      if (searchesBuilder_ == null) {
        ensureSearchesIsMutable();
        searches_.remove(index);
        onChanged();
      } else {
        searchesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public proto.Search.Builder getSearchesBuilder(
        int index) {
      return getSearchesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public proto.SearchOrBuilder getSearchesOrBuilder(
        int index) {
      if (searchesBuilder_ == null) {
        return searches_.get(index);  } else {
        return searchesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public java.util.List<? extends proto.SearchOrBuilder> 
         getSearchesOrBuilderList() {
      if (searchesBuilder_ != null) {
        return searchesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(searches_);
      }
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public proto.Search.Builder addSearchesBuilder() {
      return getSearchesFieldBuilder().addBuilder(
          proto.Search.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public proto.Search.Builder addSearchesBuilder(
        int index) {
      return getSearchesFieldBuilder().addBuilder(
          index, proto.Search.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.Search searches = 1;</code>
     */
    public java.util.List<proto.Search.Builder> 
         getSearchesBuilderList() {
      return getSearchesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Search, proto.Search.Builder, proto.SearchOrBuilder> 
        getSearchesFieldBuilder() {
      if (searchesBuilder_ == null) {
        searchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.Search, proto.Search.Builder, proto.SearchOrBuilder>(
                searches_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        searches_ = null;
      }
      return searchesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.SearchResult)
  }

  // @@protoc_insertion_point(class_scope:proto.SearchResult)
  private static final proto.SearchResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.SearchResult();
  }

  public static proto.SearchResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchResult>
      PARSER = new com.google.protobuf.AbstractParser<SearchResult>() {
    @java.lang.Override
    public SearchResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SearchResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.SearchResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

