// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/api/igdb/igdbproto.proto

package proto;

/**
 * Protobuf enum {@code proto.AgeRatingRatingEnum}
 */
public enum AgeRatingRatingEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>AGERATING_RATING_NULL = 0;</code>
   */
  AGERATING_RATING_NULL(0),
  /**
   * <code>THREE = 1;</code>
   */
  THREE(1),
  /**
   * <code>SEVEN = 2;</code>
   */
  SEVEN(2),
  /**
   * <code>TWELVE = 3;</code>
   */
  TWELVE(3),
  /**
   * <code>SIXTEEN = 4;</code>
   */
  SIXTEEN(4),
  /**
   * <code>EIGHTEEN = 5;</code>
   */
  EIGHTEEN(5),
  /**
   * <code>RP = 6;</code>
   */
  RP(6),
  /**
   * <code>EC = 7;</code>
   */
  EC(7),
  /**
   * <code>E = 8;</code>
   */
  E(8),
  /**
   * <code>E10 = 9;</code>
   */
  E10(9),
  /**
   * <code>T = 10;</code>
   */
  T(10),
  /**
   * <code>M = 11;</code>
   */
  M(11),
  /**
   * <code>AO = 12;</code>
   */
  AO(12),
  /**
   * <code>CERO_A = 13;</code>
   */
  CERO_A(13),
  /**
   * <code>CERO_B = 14;</code>
   */
  CERO_B(14),
  /**
   * <code>CERO_C = 15;</code>
   */
  CERO_C(15),
  /**
   * <code>CERO_D = 16;</code>
   */
  CERO_D(16),
  /**
   * <code>CERO_Z = 17;</code>
   */
  CERO_Z(17),
  /**
   * <code>USK_0 = 18;</code>
   */
  USK_0(18),
  /**
   * <code>USK_6 = 19;</code>
   */
  USK_6(19),
  /**
   * <code>USK_12 = 20;</code>
   */
  USK_12(20),
  /**
   * <code>USK_16 = 21;</code>
   */
  USK_16(21),
  /**
   * <code>USK_18 = 22;</code>
   */
  USK_18(22),
  /**
   * <code>GRAC_ALL = 23;</code>
   */
  GRAC_ALL(23),
  /**
   * <code>GRAC_TWELVE = 24;</code>
   */
  GRAC_TWELVE(24),
  /**
   * <code>GRAC_FIFTEEN = 25;</code>
   */
  GRAC_FIFTEEN(25),
  /**
   * <code>GRAC_EIGHTEEN = 26;</code>
   */
  GRAC_EIGHTEEN(26),
  /**
   * <code>GRAC_TESTING = 27;</code>
   */
  GRAC_TESTING(27),
  /**
   * <code>CLASS_IND_L = 28;</code>
   */
  CLASS_IND_L(28),
  /**
   * <code>CLASS_IND_TEN = 29;</code>
   */
  CLASS_IND_TEN(29),
  /**
   * <code>CLASS_IND_TWELVE = 30;</code>
   */
  CLASS_IND_TWELVE(30),
  /**
   * <code>CLASS_IND_FOURTEEN = 31;</code>
   */
  CLASS_IND_FOURTEEN(31),
  /**
   * <code>CLASS_IND_SIXTEEN = 32;</code>
   */
  CLASS_IND_SIXTEEN(32),
  /**
   * <code>CLASS_IND_EIGHTEEN = 33;</code>
   */
  CLASS_IND_EIGHTEEN(33),
  /**
   * <code>ACB_G = 34;</code>
   */
  ACB_G(34),
  /**
   * <code>ACB_PG = 35;</code>
   */
  ACB_PG(35),
  /**
   * <code>ACB_M = 36;</code>
   */
  ACB_M(36),
  /**
   * <code>ACB_MA15 = 37;</code>
   */
  ACB_MA15(37),
  /**
   * <code>ACB_R18 = 38;</code>
   */
  ACB_R18(38),
  /**
   * <code>ACB_RC = 39;</code>
   */
  ACB_RC(39),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>AGERATING_RATING_NULL = 0;</code>
   */
  public static final int AGERATING_RATING_NULL_VALUE = 0;
  /**
   * <code>THREE = 1;</code>
   */
  public static final int THREE_VALUE = 1;
  /**
   * <code>SEVEN = 2;</code>
   */
  public static final int SEVEN_VALUE = 2;
  /**
   * <code>TWELVE = 3;</code>
   */
  public static final int TWELVE_VALUE = 3;
  /**
   * <code>SIXTEEN = 4;</code>
   */
  public static final int SIXTEEN_VALUE = 4;
  /**
   * <code>EIGHTEEN = 5;</code>
   */
  public static final int EIGHTEEN_VALUE = 5;
  /**
   * <code>RP = 6;</code>
   */
  public static final int RP_VALUE = 6;
  /**
   * <code>EC = 7;</code>
   */
  public static final int EC_VALUE = 7;
  /**
   * <code>E = 8;</code>
   */
  public static final int E_VALUE = 8;
  /**
   * <code>E10 = 9;</code>
   */
  public static final int E10_VALUE = 9;
  /**
   * <code>T = 10;</code>
   */
  public static final int T_VALUE = 10;
  /**
   * <code>M = 11;</code>
   */
  public static final int M_VALUE = 11;
  /**
   * <code>AO = 12;</code>
   */
  public static final int AO_VALUE = 12;
  /**
   * <code>CERO_A = 13;</code>
   */
  public static final int CERO_A_VALUE = 13;
  /**
   * <code>CERO_B = 14;</code>
   */
  public static final int CERO_B_VALUE = 14;
  /**
   * <code>CERO_C = 15;</code>
   */
  public static final int CERO_C_VALUE = 15;
  /**
   * <code>CERO_D = 16;</code>
   */
  public static final int CERO_D_VALUE = 16;
  /**
   * <code>CERO_Z = 17;</code>
   */
  public static final int CERO_Z_VALUE = 17;
  /**
   * <code>USK_0 = 18;</code>
   */
  public static final int USK_0_VALUE = 18;
  /**
   * <code>USK_6 = 19;</code>
   */
  public static final int USK_6_VALUE = 19;
  /**
   * <code>USK_12 = 20;</code>
   */
  public static final int USK_12_VALUE = 20;
  /**
   * <code>USK_16 = 21;</code>
   */
  public static final int USK_16_VALUE = 21;
  /**
   * <code>USK_18 = 22;</code>
   */
  public static final int USK_18_VALUE = 22;
  /**
   * <code>GRAC_ALL = 23;</code>
   */
  public static final int GRAC_ALL_VALUE = 23;
  /**
   * <code>GRAC_TWELVE = 24;</code>
   */
  public static final int GRAC_TWELVE_VALUE = 24;
  /**
   * <code>GRAC_FIFTEEN = 25;</code>
   */
  public static final int GRAC_FIFTEEN_VALUE = 25;
  /**
   * <code>GRAC_EIGHTEEN = 26;</code>
   */
  public static final int GRAC_EIGHTEEN_VALUE = 26;
  /**
   * <code>GRAC_TESTING = 27;</code>
   */
  public static final int GRAC_TESTING_VALUE = 27;
  /**
   * <code>CLASS_IND_L = 28;</code>
   */
  public static final int CLASS_IND_L_VALUE = 28;
  /**
   * <code>CLASS_IND_TEN = 29;</code>
   */
  public static final int CLASS_IND_TEN_VALUE = 29;
  /**
   * <code>CLASS_IND_TWELVE = 30;</code>
   */
  public static final int CLASS_IND_TWELVE_VALUE = 30;
  /**
   * <code>CLASS_IND_FOURTEEN = 31;</code>
   */
  public static final int CLASS_IND_FOURTEEN_VALUE = 31;
  /**
   * <code>CLASS_IND_SIXTEEN = 32;</code>
   */
  public static final int CLASS_IND_SIXTEEN_VALUE = 32;
  /**
   * <code>CLASS_IND_EIGHTEEN = 33;</code>
   */
  public static final int CLASS_IND_EIGHTEEN_VALUE = 33;
  /**
   * <code>ACB_G = 34;</code>
   */
  public static final int ACB_G_VALUE = 34;
  /**
   * <code>ACB_PG = 35;</code>
   */
  public static final int ACB_PG_VALUE = 35;
  /**
   * <code>ACB_M = 36;</code>
   */
  public static final int ACB_M_VALUE = 36;
  /**
   * <code>ACB_MA15 = 37;</code>
   */
  public static final int ACB_MA15_VALUE = 37;
  /**
   * <code>ACB_R18 = 38;</code>
   */
  public static final int ACB_R18_VALUE = 38;
  /**
   * <code>ACB_RC = 39;</code>
   */
  public static final int ACB_RC_VALUE = 39;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AgeRatingRatingEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AgeRatingRatingEnum forNumber(int value) {
    switch (value) {
      case 0: return AGERATING_RATING_NULL;
      case 1: return THREE;
      case 2: return SEVEN;
      case 3: return TWELVE;
      case 4: return SIXTEEN;
      case 5: return EIGHTEEN;
      case 6: return RP;
      case 7: return EC;
      case 8: return E;
      case 9: return E10;
      case 10: return T;
      case 11: return M;
      case 12: return AO;
      case 13: return CERO_A;
      case 14: return CERO_B;
      case 15: return CERO_C;
      case 16: return CERO_D;
      case 17: return CERO_Z;
      case 18: return USK_0;
      case 19: return USK_6;
      case 20: return USK_12;
      case 21: return USK_16;
      case 22: return USK_18;
      case 23: return GRAC_ALL;
      case 24: return GRAC_TWELVE;
      case 25: return GRAC_FIFTEEN;
      case 26: return GRAC_EIGHTEEN;
      case 27: return GRAC_TESTING;
      case 28: return CLASS_IND_L;
      case 29: return CLASS_IND_TEN;
      case 30: return CLASS_IND_TWELVE;
      case 31: return CLASS_IND_FOURTEEN;
      case 32: return CLASS_IND_SIXTEEN;
      case 33: return CLASS_IND_EIGHTEEN;
      case 34: return ACB_G;
      case 35: return ACB_PG;
      case 36: return ACB_M;
      case 37: return ACB_MA15;
      case 38: return ACB_R18;
      case 39: return ACB_RC;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AgeRatingRatingEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AgeRatingRatingEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AgeRatingRatingEnum>() {
          public AgeRatingRatingEnum findValueByNumber(int number) {
            return AgeRatingRatingEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return proto.Igdbproto.getDescriptor().getEnumTypes().get(1);
  }

  private static final AgeRatingRatingEnum[] VALUES = values();

  public static AgeRatingRatingEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AgeRatingRatingEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.AgeRatingRatingEnum)
}

