// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/api/igdb/igdbproto.proto

package proto;

public interface EventLogoResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.EventLogoResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.EventLogo eventlogos = 1;</code>
   */
  java.util.List<proto.EventLogo> 
      getEventlogosList();
  /**
   * <code>repeated .proto.EventLogo eventlogos = 1;</code>
   */
  proto.EventLogo getEventlogos(int index);
  /**
   * <code>repeated .proto.EventLogo eventlogos = 1;</code>
   */
  int getEventlogosCount();
  /**
   * <code>repeated .proto.EventLogo eventlogos = 1;</code>
   */
  java.util.List<? extends proto.EventLogoOrBuilder> 
      getEventlogosOrBuilderList();
  /**
   * <code>repeated .proto.EventLogo eventlogos = 1;</code>
   */
  proto.EventLogoOrBuilder getEventlogosOrBuilder(
      int index);
}
